name: CI/CD

on:
  push:
    branches:
      - "*"

jobs:
  # build:
  #   name: Build & Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm run test

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   needs: build
  #   permissions:
  #     contents: write
  #     issues: write
  #     pull-requests: write
  #     id-token: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "lts/*"
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
  #       run: npm audit signatures
  #     - name: Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npx semantic-release

  apply:
    defaults:
      run:
        working-directory: terraform
    name: Deploy Site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        continue-on-error: false
